***ITEM 1: Año con más carreras***

In [27]:
import pandas as pd
import numpy as np
import json

In [28]:
df_races = pd.read_json(r'C:\Users\aalbe\OneDrive\Escritorio\PI01_DATA02\Datasets/races.json')

In [38]:
df_races

,raceId,year,round,circuitId,name,date,time,url
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...
...,...,...,...,...,...,...,...,...
1053,1069,2021,18,69,United States Grand Prix,2021-10-24,19:00:00,http://en.wikipedia.org/wiki/2021_United_State...
1054,1070,2021,19,32,Mexico City Grand Prix,2021-10-31,19:00:00,http://en.wikipedia.org/wiki/2021_Mexican_Gran...
1055,1071,2021,20,18,Brazilian Grand Prix,2021-11-07,17:00:00,http://en.wikipedia.org/wiki/2021_Brazilian_Gr...
1056,1072,2021,22,77,Saudi Arabian Grand Prix,2021-12-05,16:00:00,http://en.wikipedia.org/wiki/2021_Saudi_Arabia...
1057,1073,2021,23,24,Abu Dhabi Grand Prix,2021-12-12,13:00:00,http://en.wikipedia.org/wiki/2021_Abu_Dhabi_Gr...

In [39]:
# hacemos este dataframe para reducir el dataset que estamos manejando
contador_carreras = pd.DataFrame(df_races['year'].value_counts())

In [30]:
contador_carreras

      year
2021    23
2019    21
2016    21
2018    21
2012    20
...    ...
1956     8
1957     8
1961     8
1950     7
1955     7

[72 rows x 1 columns]

In [31]:
# reseteamos el indice para que el año pase a ser una columna
contador_carreras.reset_index(inplace=True)

In [32]:
# cambiamos de nombre las columnas
contador_carreras.rename({'year': 'repeticiones'}, axis=1, inplace=True)

In [33]:
contador_carreras.rename({'index': 'year'}, axis=1, inplace=True)

In [34]:
contador_carreras

    year  repeticiones
0   2021            23
1   2019            21
2   2016            21
3   2018            21
4   2012            20
..   ...           ...
67  1956             8
68  1957             8
69  1961             8
70  1950             7
71  1955             7

[72 rows x 2 columns]

In [35]:
# máscara que muestra mayores repeticiones
mayor_repeticion = contador_carreras['repeticiones'] == contador_carreras['repeticiones'].max()

In [36]:
# filtramos el año de mayor repetición
int(contador_carreras[mayor_repeticion]['year'].to_string(index = False))

2021

In [37]:
# entonces queda:
print('el año con mayor repeticiones es', int(contador_carreras[mayor_repeticion]['year'].to_string(index = False)), 'con un total de', contador_carreras['repeticiones'].max(), 'repeticiones')

el año con mayor repeticiones es 2021 con un total de 23 repeticiones